authentication/urls.py
from django.urls import path
from authentication.views import LoginView,RegisterView,LogoutView
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login',LoginView.as_view(),name='login'),
    path('register',RegisterView.as_view(),name='register'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('activate/<slug:uidb64>/<slug:token>',views.activate_user,name='activate'),
    ]

core/urls.py
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView,TokenVerifyView
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('api/token/',TokenObtainPairView.as_view()),
    path('api/token/refresh/',TokenRefreshView.as_view()),
    path('api/token/verify/',TokenVerifyView.as_view()),
    path('admin/', admin.site.urls),
    path('',include('budget.urls')),
    path('authentication/',include('authentication.urls'))
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin

# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self,email,username,password=None):
        """creates and saves a user 
           based on email and password provided"""
        if not email:
            raise ValueError('Email must be provided')
        email = self.normalize_email(email)
        email = email.lower()

        user = self.model(
            email=email,
            username = username,

        )
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self,email,username,password=None):
        """creates and saves super users"""
        user = self.create_user(email,username,password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(max_length=50,unique=True)
    username = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    


    def __str__(self):
        return self.email

authentication/forms.py
from django import forms
from django.forms import  ModelForm
from budget.models import Owner
from .validators import password_validation
from django.contrib.auth.forms import UserCreationForm



class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = Owner
        fields = ['first_name','last_name','username','owner','gender','phone_no','code','address','county','town']

    def clean_username(self):
        uname = self.cleaned_data.get('username').lower()
        if Owner.objects.filter(username__iexact=uname).exists():
            raise forms.ValidationError('Username already exists')
        return uname

    def clean_email(self):
        email = self.cleaned_data['owner'].lower()
        if Owner.objects.filter(owner=email).exists():
            raise forms.ValidationError('email has been taken')

        return email


class MyLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

authentication/views.py
from django.shortcuts import render,redirect,resolve_url
from django.views.generic import FormView,View,CreateView
from authentication.forms import RegisterForm,MyLoginForm
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import logout,login,authenticate,get_user_model
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_str
from authentication.tokens import account_activation_token
from budget.utils import RegisterLoginPagesMixin,SuccessMessageMixin
from django.conf import settings
from rest_framework import permissions
from django.core.exceptions import ValidationError
from django.contrib import messages
from .tokens import account_activation_token
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect
# # Create your views here.

User = get_user_model()

def activation_email(User,request):
        current_site = get_current_site(request)
        email_subject = 'Activate your account'
        email_body = render_to_string('activate-email.html',{
            'User':User,
            'domain':current_site,
            'uid':urlsafe_base64_encode(force_bytes(User.pk)),
            'token':account_activation_token.make_token(User) 
        })

        
        email = EmailMessage(subject=email_subject,body=email_body,
                             from_email=settings.EMAIL_FROM_USER,to=[User.email])
        print(email)
        email.send()

class RegisterView(RegisterLoginPagesMixin,SuccessMessageMixin,CreateView):
    template_name = 'authentication/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('budget:home-user')
    permission_classes = (permissions.AllowAny, )
    success_message = 'user created successfully'

    def form_valid(self, form):
            username = form.cleaned_data.get('username')
            fname = form.cleaned_data.get('first_name')
            lname = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('owner')
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            
            if password == confirm_password:
                
                user = User.objects.create_user(email=email,username=username,password=password)
                form.instance.user = user
                instance = form.save(commit=False)
                form.save()
                
                activation_email(user,self.request)
                messages.add_message(self.request,messages.SUCCESS,
                "We've sent you an email to verify your account")
                return redirect('authentication:login')
            else:
                raise ValidationError(self.request,'Password fields must match')
        


def activate_user(request,uidb64,token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except Exception as e:
        user=None

    if user and account_activation_token.check_token(user,token):
        user.email_verified=True
        user.save()

        messages.add_message(request,messages.SUCCESS,
        'Email verified,you can now login')
        return redirect('authentication:login')

    return render(request,'activate-failed.html',{'user':user}) 

class LoginView(RegisterLoginPagesMixin,FormView):
    """
    Display the login form and handle the login action.
    """
    next_page = 'budget:home-user'
    template_name = 'authentication/login.html'
    form_class = MyLoginForm
    success_url = reverse_lazy('budget:home-user')
    redirect_authenticated_user = False
    extra_context = None


    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    


    def form_valid(self, form):
        uname = form.cleaned_data.get('username')
        pword = form.cleaned_data.get('password')
        usr = authenticate(self.request,username=uname,password=pword)
        if not usr.email_verified:
            messages.add_message(self.request,messages.ERROR,
            'Email is not verified')
            return render(self.request,'activate-email.html')
        if usr is not None:
            login(self.request,usr)
        else:
            return render(self.request,self.template_name,{'form':self.form_class,'error':'invalid credentials'})
        return super().form_valid(form)

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        else:
            return resolve_url(settings.LOGIN_REDIRECT_URL)


class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect('budget:home-guest')

authentication/templates/activate-email.html
{% load static %}
{% autoescape off %}


    Hi {{User.name}}

    Please use the link below to verify your account.

    http://{{domain}}{% url 'authentication:activate' uidb64=uid token=token %}

{% endautoescape %}

authentication/templates/activate-failed.html
<p>Something went wrong,Kindly request another link</p>

authentication/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Fflic - Budget</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.icon' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
                           
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body>
                           
    <div class="container-fluid position-relative d-flex p-0">
        <!-- {% include 'partials/_spinner.html' %} -->
        <!-- Content Start -->
        {% include 'partials/_sidebar.html' %}
        <div class="content">
            {% include 'partials/_header.html' %}
            {% block content %}
            {% endblock %}


                           

        </div>
        <!-- Content End -->



        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/chart/chart.min.js' %}"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
        <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
        <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

        <!-- Template Javascript -->
        {{actual_income| json_script:"income"}}
        {{expense_total| json_script:"expense"}}
        {{debt_total| json_script:"debt"}}
        {{expense_months| json_script:"months"}}
        <!-- <script src="{% static 'js/main.js' %}"></script> -->
        <script src="{% static 'js/my-mainss.js' %}"></script>
</body>

</html>
                   

authentication/templates/d.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Form Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Add Income</h6>
                <div class="form-reg">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{forms.income}}
                        <button class="appointment-btn">Add Income</button>
                    </form>
                </div>

            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Add Expenses</h6>
                <form action="" method="post">
                    {% csrf_token %}
                    {{forms.expense}}
                    <button class="appointment-btn">Add Expense</button>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Floating Label</h6>
            <form action="" method="post">
                {% csrf_token %}
                {{forms.expense}}
                <button class="appointment-btn">Add Expense</button>
            </form>
             <div class="form-floating">
                    <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea"
                        style="height: 150px;"></textarea>
                    <label for="floatingTextarea">Comments</label>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">File Input</h6>
                <div class="mb-3">
                    <label for="formFile" class="form-label">Default file input example</label>
                    <input class="form-control bg-dark" type="file" id="formFile">
                </div>
                <div class="mb-3">
                    <label for="formFileMultiple" class="form-label">Multiple files input example</label>
                    <input class="form-control bg-dark" type="file" id="formFileMultiple" multiple>
                </div>
                <div class="mb-3">
                    <label for="formFileSm" class="form-label">Small file input example</label>
                    <input class="form-control form-control-sm bg-dark" id="formFileSm" type="file">
                </div>
                <div>
                    <label for="formFileLg" class="form-label">Large file input example</label>
                    <input class="form-control form-control-lg bg-dark" id="formFileLg" type="file">
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Select</h6>
                <select class="form-select form-select-sm mb-3" aria-label=".form-select-sm example">
                    <option selected>Open this select menu</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                </select>
                <select class="form-select mb-3" aria-label="Default select example">
                    <option selected>Open this select menu</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                </select>
                <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                    <option selected>Open this select menu</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                </select>
                <select class="form-select" multiple aria-label="multiple select example">
                    <option selected>Open this select menu</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                </select>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Check, Radio & Switch</h6>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Default checkbox
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
                    <label class="form-check-label" for="flexCheckChecked">
                        Checked checkbox
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
                    <label class="form-check-label" for="inlineCheckbox1">1</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
                    <label class="form-check-label" for="inlineCheckbox2">2</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3" disabled>
                    <label class="form-check-label" for="inlineCheckbox3">3 (disabled)</label>
                </div>
                <hr>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1">
                        Default radio
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                    <label class="form-check-label" for="flexRadioDefault2">
                        Default checked radio
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1"
                        value="option1">
                    <label class="form-check-label" for="inlineRadio1">1</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2"
                        value="option2">
                    <label class="form-check-label" for="inlineRadio2">2</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3"
                        value="option3" disabled>
                    <label class="form-check-label" for="inlineRadio3">3 (disabled)</label>
                </div>
                <hr>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Default switch checkbox
                        input</label>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
                    <label class="form-check-label" for="flexSwitchCheckChecked">Checked switch checkbox
                        input</label>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDisabled" disabled>
                    <label class="form-check-label" for="flexSwitchCheckDisabled">Disabled switch checkbox
                        input</label>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckCheckedDisabled"
                        checked disabled>
                    <label class="form-check-label" for="flexSwitchCheckCheckedDisabled">Disabled checked
                        switch checkbox input</label>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Input Group</h6>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1">@</span>
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username"
                        aria-describedby="basic-addon1">
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Recipient's username"
                        aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <span class="input-group-text" id="basic-addon2">@example.com</span>
                </div>
                <label for="basic-url" class="form-label">Your vanity URL</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon3">https://example.com/users/</span>
                    <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text">$</span>
                    <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
                    <span class="input-group-text">.00</span>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Username" aria-label="Username">
                    <span class="input-group-text">@</span>
                    <input type="text" class="form-control" placeholder="Server" aria-label="Server">
                </div>
                <div class="input-group">
                    <span class="input-group-text">With textarea</span>
                    <textarea class="form-control" aria-label="With textarea"></textarea>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-xl-6">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Sizing</h6>
                <input class="form-control form-control-lg mb-3" type="text" placeholder=".form-control-lg"
                    aria-label=".form-control-lg example">
                <input class="form-control mb-3" type="text" placeholder="Default input"
                    aria-label="default input example">
                <input class="form-control form-control-sm" type="text" placeholder=".form-control-sm"
                    aria-label=".form-control-sm example">
            </div>
        </div>
    </div>
</div>
<!-- Form End -->

{% endblock %}

authentication/templates/home-guest.html
{% load static %}
{% include 'partials/_sidebar.html' %}
<!-- Template Stylesheet -->
<link href="{% static 'css/styles.css' %}" rel="stylesheet">
<!-- Favicon -->
<link href="{% static 'img/favicon.icon' %}" rel="icon">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
    rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<link href="{% static 'css/styles.css' %}" rel="stylesheet">

{% block content %}
<section class="home-container">
    <div class="user-summary">
        <div class="user-card">
            <h1>Welcome Guest</h1>
            <h1>What do you do?</h1>
            <img src="{% static 'img/user.jpg'%}" class="user-img-guest" alt="">
            <h3>User status is False</h3>
        </div>
        <div class="expense-cards">
            <a href="">
                <div class="income-card">
                    <h1>Monthly Income</h1>
                    <h2>ksh.0</h2>
                    <img src="" alt="">
                    <p>User status is False!</p>
            </a>
        </div>
        <a href="">
            <div class="debt-card">
                <h1>Monthly Debt</h1>
                <h2>ksh.0</h2>
                <img src="" alt="">
                <p>User status is False!</p>
        </a>
    </div>
    <a href="">
        <div class="expense-card">
            <h1>Monthly Expenses</h1>
            <h2>ksh.0</h2>
            <img src="" alt="">
            <p>User status is False!</p>
    </a></div>

    </div>
    </div>
    <div class="summary-calendar">
        <div class="summary-graph">
            <img src="{% static 'images/test.jpg' %}" class="graph" alt="">
        </div>
        <div class="calendar-card">
            <img src="{% static 'images/test.jpg' %}" class="calendar" alt="">
        </div>
    </div>
</section>
{% endblock %}