authentication/urls.py
from django.urls import path
from authentication.views import LoginView,RegisterView,LogoutView
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login',LoginView.as_view(),name='login'),
    path('register',RegisterView.as_view(),name='register'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('activate/<slug:uidb64>/<slug:token>',views.activate_user,name='activate'),
    ]

budget/urls.py
from django.urls import path
from .views import HomeGuest,MyUserProfile,HomeView,AllForms,AllTables,DebtView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'budget'

urlpatterns = [
    path('',HomeGuest.as_view(),name='home-guest'),
    path('home-user',HomeView.as_view(),name='home-user'),
    path('debt',DebtView.as_view(),name='debt'),
    path('forms',AllForms.as_view(),name='forms'),

    path('tables',AllTables.as_view(),name='tables'),
    path('user-profile',MyUserProfile.as_view(),name='user-profile'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView,TokenVerifyView
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('api/token/',TokenObtainPairView.as_view()),
    path('api/token/refresh/',TokenRefreshView.as_view()),
    path('api/token/verify/',TokenVerifyView.as_view()),
    path('admin/', admin.site.urls),
    path('',include('budget.urls')),
    path('authentication/',include('authentication.urls'))
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin

# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self,email,username,password=None):
        """creates and saves a user 
           based on email and password provided"""
        if not email:
            raise ValueError('Email must be provided')
        email = self.normalize_email(email)
        email = email.lower()

        user = self.model(
            email=email,
            username = username,

        )
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self,email,username,password=None):
        """creates and saves super users"""
        user = self.create_user(email,username,password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(max_length=50,unique=True)
    username = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    


    def __str__(self):
        return self.email

authentication/forms.py
from django import forms
from django.forms import  ModelForm
from budget.models import Owner
from .validators import password_validation
from django.contrib.auth.forms import UserCreationForm



class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = Owner
        fields = ['first_name','last_name','username','owner','gender','phone_no','code','address','county','town']

    def clean_username(self):
        uname = self.cleaned_data.get('username').lower()
        if Owner.objects.filter(username__iexact=uname).exists():
            raise forms.ValidationError('Username already exists')
        return uname

    def clean_email(self):
        email = self.cleaned_data['owner'].lower()
        if Owner.objects.filter(owner=email).exists():
            raise forms.ValidationError('email has been taken')

        return email


class MyLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

authentication/views.py
from django.shortcuts import render,redirect,resolve_url
from django.views.generic import FormView,View,CreateView
from authentication.forms import RegisterForm,MyLoginForm
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import logout,login,authenticate,get_user_model
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_str
from authentication.tokens import account_activation_token
from budget.utils import RegisterLoginPagesMixin,SuccessMessageMixin
from django.conf import settings
from rest_framework import permissions
from django.core.exceptions import ValidationError
from django.contrib import messages
from .tokens import account_activation_token
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect
# # Create your views here.

User = get_user_model()

def activation_email(User,request):
        current_site = get_current_site(request)
        email_subject = 'Activate your account'
        email_body = render_to_string('activate-email.html',{
            'User':User,
            'domain':current_site,
            'uid':urlsafe_base64_encode(force_bytes(User.pk)),
            'token':account_activation_token.make_token(User) 
        })

        
        email = EmailMessage(subject=email_subject,body=email_body,
                             from_email=settings.EMAIL_FROM_USER,to=[User.email])
        print(email)
        email.send()

class RegisterView(RegisterLoginPagesMixin,SuccessMessageMixin,CreateView):
    template_name = 'authentication/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('budget:home-user')
    permission_classes = (permissions.AllowAny, )
    success_message = 'user created successfully'

    def form_valid(self, form):
            username = form.cleaned_data.get('username')
            fname = form.cleaned_data.get('first_name')
            lname = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('owner')
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            
            if password == confirm_password:
                
                user = User.objects.create_user(email=email,username=username,password=password)
                form.instance.user = user
                instance = form.save(commit=False)
                form.save()
                
                activation_email(user,self.request)
                messages.add_message(self.request,messages.SUCCESS,
                "We've sent you an email to verify your account")
                return redirect('authentication:login')
            else:
                raise ValidationError(self.request,'Password fields must match')
        


def activate_user(request,uidb64,token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except Exception as e:
        user=None

    if user and account_activation_token.check_token(user,token):
        user.email_verified=True
        user.save()

        messages.add_message(request,messages.SUCCESS,
        'Email verified,you can now login')
        return redirect('authentication:login')

    return render(request,'activate-failed.html',{'user':user}) 

class LoginView(RegisterLoginPagesMixin,FormView):
    """
    Display the login form and handle the login action.
    """
    next_page = 'budget:home-user'
    template_name = 'authentication/login.html'
    form_class = MyLoginForm
    success_url = reverse_lazy('budget:home-user')
    redirect_authenticated_user = False
    extra_context = None


    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    


    def form_valid(self, form):
        uname = form.cleaned_data.get('username')
        pword = form.cleaned_data.get('password')
        usr = authenticate(self.request,username=uname,password=pword)
        if not usr.email_verified:
            messages.add_message(self.request,messages.ERROR,
            'Email is not verified')
            return render(self.request,'activate-email.html')
        if usr is not None:
            login(self.request,usr)
        else:
            return render(self.request,self.template_name,{'form':self.form_class,'error':'invalid credentials'})
        return super().form_valid(form)

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        if self.next_page:
            return resolve_url(self.next_page)
        else:
            return resolve_url(settings.LOGIN_REDIRECT_URL)


class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect('budget:home-guest')

authentication/templates/partials/_footer.html
{% load static%}


{% block content %}

<!-- Footer Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded-top p-4">
        <div class="row">
            <div class="col-12 col-sm-6 text-center text-sm-start">
                &copy; <a href="#">Your Site Name</a>, All Right Reserved.
            </div>
            <div class="col-12 col-sm-6 text-center text-sm-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

{% endblock %}

authentication/templates/partials/_header.html
{% load static%}


{% block content %}
<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
    <a href="{% url 'budget:home-guest' %}" class="navbar-brand d-flex d-lg-none me-4">
        <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
    </a>
    <a href="{% url 'budget:home-guest' %}" class="toggle flex-shrink-0">
        <i class="fa fa-bars"></i>
    </a>
    <form class="d-none d-md-flex ms-4">
        <input class="form-control bg-dark border-0" type="search" placeholder="Search">
    </form>
    <div class="navbar-nav align-items-center ms-auto">
        {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-envelope me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Message</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{{owner.userprofile.image.url}}" alt="profile pic" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Benna sent you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{{owner.userprofile.image.url}}" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Benna sent you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{{owner.userprofile.image.url}}" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Benna sent you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all message</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-bell me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Notification</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Profile updated</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">New user added</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Password changed</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all notifications</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <img class="rounded-circle me-lg-2" src="{{owner.userprofile.image.url}}" alt="" style="width: 40px; height: 40px;">
                <span class="d-none d-lg-inline-flex">{{request.user.username}}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="{% url 'budget:user-profile' %}" class="dropdown-item">My Profile</a>
                <a href="#" class="dropdown-item">Settings</a>
                <a href="{% url 'authentication:logout' %}" class="dropdown-item">Log Out</a>
                {% else %}
                <a href="{% url 'authentication:register' %}">
                    <li>Register | </li>
                </a>
                <a href="{% url 'authentication:login' %}">
                    <li> Login</li>
                </a>
            </div>
        </div>
        {% endif %}
    </div>
</nav>
<!-- Navbar End -->

{% endblock %}

authentication/templates/partials/_sidebar.html
{% load static%}


{% block content %}

<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-secondary navbar-dark">
        <a href="{% url 'budget:home-guest' %}" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Fflic</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                {% if request.user.is_anonymous %}
                <a href="{% url 'budget:user-profile' %}"><img class="rounded-circle" src="{% static 'img/user.jpg' %}"
                        alt="" style="width: 40px; height: 40px;"></a>
                {% else %}
                <a href="{% url 'budget:user-profile' %}"><img class="rounded-circle"
                        src="{{owner.userprofile.image.url}}" alt="" style="width: 40px; height: 40px;"></a>

                {% endif %}

                <div
                    class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                </div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{{request.user.username}}</h6>

            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'budget:home-user' %}" class="nav-item nav-link active"><i
                    class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i
                        class="fa fa-laptop me-2"></i>Elements</a>
                <div class="dropdown-menu bg-transparent border-0">
                    <a href="button.html" class="dropdown-item">Buttons</a>
                    <a href="typography.html" class="dropdown-item">Typography</a>
                    <a href="element.html" class="dropdown-item">Other Elements</a>
                </div>
            </div>
            <a href="{% url 'budget:user-profile' %}" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Add
                Data</a>
            <a href="{% url 'budget:forms' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Forms</a>
            <a href="{% url 'budget:tables' %}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
            <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>
            <div class="nav-item dropdown">
                {% if request.user.is_anonymous %}
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i
                        class="far fa-file-alt me-2"></i>Pages</a>
                <div class="dropdown-menu bg-transparent border-0">
                    <a href="{% static 'authentication/login.html' %}" class="dropdown-item">Sign In</a>
                    <a href="{% static 'authentication/register.html' %}" class="dropdown-item">Sign Up</a>
                    <a href="404.html" class="dropdown-item">404 Error</a>
                    <a href="blank.html" class="dropdown-item">Blank Page</a>
                </div>
                {% endif%}

            </div>
        </div>
    </nav>
</div>
<!-- Sidebar End -->
{% endblock %}

authentication/templates/partials/_spinner.html
{% load static %}
{% block content %}

<!-- Spinner Start -->
<!-- <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div> -->
<!-- Spinner End -->

{% endblock %}